apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      initContainers:
        - name: clone-repo
          image: alpine/git
          command:
            - sh
            - -c
            - |
              git clone https://github.com/dimitriytiho/kuber.git /var/www/html &&
              chown -R 82:82 /var/www/html  # 82 = UID пользователя www-data в php-fpm
          volumeMounts:
            - name: app-data
              mountPath: /var/www/html
      containers:
        - name: php-fpm
          image: php:8.2-fpm
          volumeMounts:
            - name: app-data
              mountPath: /var/www/html
        - name: nginx
          image: nginx:alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: app-data
              mountPath: /var/www/html
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: nginx.conf
      volumes:
        - name: app-data
          emptyDir: {}
        - name: nginx-config
          configMap:
            name: nginx-config